# 1. CLOUD DATABASE CONNECTION
# Railway will automatically fill these in. Do not change them.
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. HIBERNATE (Database Setup)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. PORT
# Railway assigns a random port, this lets it handle that.
server.port=${PORT:8080}