# 1. DATABASE CONNECTION
# Railway will automatically fill these ${} values for you
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. HIBERNATE SETTINGS
# This tells Java to create the tables in the cloud database automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. SERVER SETTINGS
# Railway picks a random port for your app, this line handles it
server.port=${PORT:8080}