spring.datasource.url=jdbc:mysql://localhost:3306/Tamilnadu_Database
spring.datasource.username=root
spring.datasource.password=01052004Mani.1mks
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
